services:
  # ========================
  # FRONTEND (Next.js)
  # ========================
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    image: benjaphan-frontend:latest
    restart: always
    networks:
      - benjaphan-network
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    container_name: frontend
    volumes:
      - frontend_cache:/app/.next

  # ========================
  # DASHBOARD (React + Vite)
  # ========================
  dashboard:
    build:
      context: ./Dashboard
      dockerfile: Dockerfile
    image: benjaphan-dashboard:latest
    restart: always
    networks:
      - benjaphan-network
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    container_name: dashboard
    volumes:
      - dashboard_cache:/app/dist
      
  # ========================
  # BACKEND (Express + TypeScript)
  # ========================
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    image: benjaphan-backend:latest
    restart: always
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID}
      - FACEBOOK_CLIENT_SECRET=${FACEBOOK_CLIENT_SECRET}
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - mongo
    networks:
      - benjaphan-network
    container_name: backend
    volumes:
      - backend_uploads:/app/uploads

  # ========================
  # MONGO DATABASE
  # ========================
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "3001:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: benjaphan5
    volumes:
      - mongo-data:/data/db
      - ./dump:/dump
    networks:
      - benjaphan-network
    container_name: mongo

  # ========================
  # nginx
  # ========================
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/cert/origin.pem:/etc/nginx/cert/origin.pem:ro
      - ./nginx/cert/private.key:/etc/nginx/cert/private.key:ro
    depends_on:
      - frontend
      - dashboard
      - backend
    networks:
      - benjaphan-network

# ========================
# VOLUME
# ========================
volumes:
  mongo-data:
  backend_uploads:
  frontend_cache:
  dashboard_cache:

# ========================
# NETWORK
# ========================
networks:
  benjaphan-network:
    driver: bridge
